package com.cglia.model;
// Generated Jul 25, 2023, 3:22:03 PM by Hibernate Tools 6.0.2.Final

/**
 * Books generated by hbm2java
 */
public class Books implements java.io.Serializable {

	private int bookId;
	private String bookName;
	private String author;
	private int yearOfPublication;
	private int price;
	private String bookstatus;

	public Books() {
	}

	public Books(int bookId, String bookName, String author, int yearOfPublication, int price, String bookstatus) {
		this.bookId = bookId;
		this.bookName = bookName;
		this.author = author;
		this.yearOfPublication = yearOfPublication;
		this.price = price;
		this.bookstatus = bookstatus;
	}

	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public int getYearOfPublication() {
		return this.yearOfPublication;
	}

	public void setYearOfPublication(int yearOfPublication) {
		this.yearOfPublication = yearOfPublication;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public String getBookstatus() {
		return this.bookstatus;
	}

	public void setBookstatus(String bookstatus) {
		this.bookstatus = bookstatus;
	}

}
