package com.cglia.model;
// Generated Jul 25, 2023, 3:22:03 PM by Hibernate Tools 6.0.2.Final

/**
 * Bookrequest generated by hbm2java
 */
public class Bookrequest implements java.io.Serializable {

	private int bookid;
	private int userid;
	private String username;
	private String bookname;
	private String bookstatus;

	public Bookrequest() {
	}

	public Bookrequest(int bookid, int userid, String username, String bookname, String bookstatus) {
		this.bookid = bookid;
		this.userid = userid;
		this.username = username;
		this.bookname = bookname;
		this.bookstatus = bookstatus;
	}

	public int getBookid() {
		return this.bookid;
	}

	public void setBookid(int bookid) {
		this.bookid = bookid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getBookname() {
		return this.bookname;
	}

	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	public String getBookstatus() {
		return this.bookstatus;
	}

	public void setBookstatus(String bookstatus) {
		this.bookstatus = bookstatus;
	}

}
