package com.cglia.model;
// Generated Jul 25, 2023, 3:22:03 PM by Hibernate Tools 6.0.2.Final

/**
 * Bookissue generated by hbm2java
 */
public class Bookissue implements java.io.Serializable {

	private int userId;
	private String bookName;
	private String username;
	private String price;
	private String bookStatus;

	public Bookissue() {
	}

	public Bookissue(int userId, String bookName, String username, String price, String bookStatus) {
		this.userId = userId;
		this.bookName = bookName;
		this.username = username;
		this.price = price;
		this.bookStatus = bookStatus;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getBookStatus() {
		return this.bookStatus;
	}

	public void setBookStatus(String bookStatus) {
		this.bookStatus = bookStatus;
	}

}
