package com.cglia.model;
// Generated Jul 25, 2023, 3:22:03 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private long id;
	private String title;
	private Set stories = new HashSet(0);

	public Book() {
	}

	public Book(long id) {
		this.id = id;
	}

	public Book(long id, String title, Set stories) {
		this.id = id;
		this.title = title;
		this.stories = stories;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set getStories() {
		return this.stories;
	}

	public void setStories(Set stories) {
		this.stories = stories;
	}

}
