package com.cglia.model;
// Generated Jul 25, 2023, 3:22:03 PM by Hibernate Tools 6.0.2.Final

/**
 * Buyer generated by hbm2java
 */
public class Buyer implements java.io.Serializable {

	private Integer buyerId;
	private String email;
	private String password;

	public Buyer() {
	}

	public Buyer(String email, String password) {
		this.email = email;
		this.password = password;
	}

	public Integer getBuyerId() {
		return this.buyerId;
	}

	public void setBuyerId(Integer buyerId) {
		this.buyerId = buyerId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
