package com.cglia.model;
// Generated Jul 25, 2023, 3:22:03 PM by Hibernate Tools 6.0.2.Final

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer CId;
	private String CName;
	private String CEmail;
	private long CPhone;

	public Customer() {
	}

	public Customer(String CName, String CEmail, long CPhone) {
		this.CName = CName;
		this.CEmail = CEmail;
		this.CPhone = CPhone;
	}

	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	public String getCEmail() {
		return this.CEmail;
	}

	public void setCEmail(String CEmail) {
		this.CEmail = CEmail;
	}

	public long getCPhone() {
		return this.CPhone;
	}

	public void setCPhone(long CPhone) {
		this.CPhone = CPhone;
	}

}
