package com.cglia.model;
// Generated Jul 25, 2023, 3:22:03 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Employ generated by hbm2java
 */
public class Employ implements java.io.Serializable {

	private Long id;
	private Department department;
	private String name;
	private Set departments = new HashSet(0);

	public Employ() {
	}

	public Employ(Department department, String name, Set departments) {
		this.department = department;
		this.name = name;
		this.departments = departments;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set departments) {
		this.departments = departments;
	}

}
