package com.cglia.model;
// Generated Jul 25, 2023, 3:22:03 PM by Hibernate Tools 6.0.2.Final

/**
 * Story generated by hbm2java
 */
public class Story implements java.io.Serializable {

	private long id;
	private Book book;
	private String content;

	public Story() {
	}

	public Story(long id) {
		this.id = id;
	}

	public Story(long id, Book book, String content) {
		this.id = id;
		this.book = book;
		this.content = content;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
