package com.cglia.model;
// Generated Jul 25, 2023, 3:22:03 PM by Hibernate Tools 6.0.2.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userId;
	private String userName;
	private int age;
	private String gender;
	private String email;
	private String state;
	private String city;
	private String password;

	public User() {
	}

	public User(int userId, String userName, int age, String gender, String email, String state, String city,
			String password) {
		this.userId = userId;
		this.userName = userName;
		this.age = age;
		this.gender = gender;
		this.email = email;
		this.state = state;
		this.city = city;
		this.password = password;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
